In [4]:

import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

# 固定种子，方便结果复现
np.random.seed(77)

In [5]:
a1 = np.array([[1,2,3],[4,5,6]])
# print(a1.dot(np.linalg.pinv(a1)).dot(a1))
u, s, v = np.linalg.svd(a1)
print(u.shape)
ss = np.hstack((np.diag(s), np.zeros((2,1))))
print(ss)
print(u.dot(ss).dot(v))
print("*********************")
print(a1)
print((a1)[1, :])
print((a1)[(1,), :])
a1.T




(2, 2)
[[9.508032   0.         0.        ]
 [0.         0.77286964 0.        ]]
[[1. 2. 3.]
 [4. 5. 6.]]
*********************
[[1 2 3]
 [4 5 6]]
[4 5 6]
[[4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:

people_dict = {
    "weight": pd.Series([68, 83, 112], index=["alice", "bob", "charles"]),
    "birthyear": pd.Series([1984, 1985, 1992], index=["bob", "alice", "charles"], name="year"),
    "children": pd.Series([0, 3], index=["charles", "bob"]),
    "hobby": pd.Series(["Biking", "Dancing"], index=["alice", "bob"]),
}
people = pd.DataFrame(people_dict)
print(people)
people.loc["alice", "birthyear"] = 2024

print(people.loc[("alice", "charles"), :].loc[:, ("weight", "children")])

people.fillna(11)
print(type(people.loc["alice", "children"]))

print("-------------------")
print(people.isnull().any(axis=0))
print(people.info())
print(people.loc[:, "children"].fillna(1000))

people.loc[:, "children"] = people.loc[:, "children"].fillna(1000)
print(people)



         weight  birthyear  children    hobby
alice        68       1985       NaN   Biking
bob          83       1984       3.0  Dancing
charles     112       1992       0.0      NaN
         weight  children
alice        68       NaN
charles     112       0.0
<class 'numpy.float64'>
-------------------
weight       False
birthyear    False
children      True
hobby         True
dtype: bool
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, alice to charles
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   weight     3 non-null      int64  
 1   birthyear  3 non-null      int64  
 2   children   2 non-null      float64
 3   hobby      2 non-null      object 
dtypes: float64(1), int64(2), object(1)
memory usage: 228.0+ bytes
None
alice      1000.0
bob           3.0
charles       0.0
Name: children, dtype: float64
         weight  birthyear  children    hobby
alice        68       2024    1000.0   Biking
bob         

In [12]:
matrix = people.iloc[:, 0:3]
print(matrix)
print(np.linalg.inv(matrix))




         weight  birthyear  children
alice        68       2024    1000.0
bob          83       1984       3.0
charles     112       1992       0.0
[[ 1.05586203e-04 -3.51954009e-02  3.49467715e-02]
 [-5.93657365e-06  1.97885788e-03 -1.46287069e-03]
 [ 1.00483576e-03 -1.61192109e-03  5.84469810e-04]]
